### ISSUE TITLE
Standalone demos needed.

### ISSUE THREAD

**Issue by paul-hammant** [yawaramin/stubbex#2]
That this is Phoenix/Elixir/Erlang/BEAM based is **very cool of course**. To Java, Ruby, Python, C# people in enterprise-land they'll want to know how to hook it up from their build's point of view.

Bootsrapping off the efforts of others is very smart. Former colleage Pete Hodgeson made https://www.todobackend.com/ and I think it's a fantastic addition to the "TodoMVC" comparison idea. He's chose one frontend (Backbone) as the one that's the reference impl for the alternate backends. He had to extend it to actually do REST (Addy Osami's TodoMVC made not wire calls - just used local storage), but you can try it and the Jasmine specs against any of the backends

This is a gift to you - could you record one of the 'reals' and make a Stubbex thing that passes the Jasmine specs?  Yes of course, but the Bash/Maven/Rake/Pybuild/MsBuild fu will be missing to others that would otherwise wish to benefit from the process orchestration examples. 

It is cohesive example code that takes you from 'interesting' to winning.

By the way, the OSS alternatives to SV include:

* https://github.com/SpectoLabs/hoverfly (London startup trying to sell services too)
* https://github.com/tomakehurst/wiremock (long established, Java leaning)
* https://github.com/epam/Wilma - EPAM is a big FS consultancy
* https://github.com/BaiduQA/terminator 
* https://github.com/Nike-Inc/bokor  

Commercial players include:

* CA's "Lisa"
* Smartbear

**Comment by yawaramin** [comment]
Hi Paul, thank you, this is very useful. I took a look at the alternatives here and they seem powerful but complex. Complexity and configurability seem to be the state of the art in this space. Even the simplest stub recording tool that I looked at, Wiremock, requires you to go through multiple steps and only records one host at a time. I badly wanted a simpler alternative, and Stubbex was born out of that.

Now, as to your point about a working example, it's a good point, but any given example would necessarily need to be specific to a stack. Instead, I decided to write up a birds-eye view of the developer workflow which people should be able to customize to suit their needs. For now, I think it's a reasonable start. In the future, I may well write up wiki pages with more detailed usage.

**Comment by paul-hammant** [comment]
Sure, but adoption drops off 95% if there no example to copy :-(

It depends what your personal plans were - if you're wanting to quit your day job and earn a revenue stream from Stubbex, then you need a certain amount of critical mass.
